### ISSUE TITLE
where do i get docker version of nodebb?

### ISSUE THREAD

**Issue by ralyodio** [NodeBB/NodeBB#10633]
where do i get docker version of nodebb?

**Comment by ralyodio** [comment]
I see we have a docker-compose.yml file: i get this error:

```
node_1  | Now configuring mongo database:
node_1  | 2022-05-19T23:21:50.834Z [19] - warn: NodeBB Setup Aborted.
node_1  |  MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
node_1  |     at Timeout._onTimeout (/usr/src/app/node_modules/mongodb/lib/sdam/topology.js:305:38)
node_1  |     at listOnTimeout (node:internal/timers:559:17)
node_1  |     at processTimers (node:internal/timers:502:7)
```

here is my docker-compose.yml

```
version: '3.5'

services:
  node:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8037:4567

  db:
    image: mongo:bionic
    restart: unless-stopped
    ports:
      - 8038:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo:/data/db

volumes:
  mongo:

```
