### ISSUE TITLE
Substitute bind_address as NODEBB_BIND_ADDRESS environmental variables

### ISSUE THREAD

**Issue by stevefan1999-personal** [NodeBB/NodeBB#12757]
### Description

I have a problem with Kubernetes, and for some reason the service IP was listened to due to wildcard match with 0.0.0.0 -- and obviously this is an access denied:
```
2024-08-26T06:35:11.996Z [tcp://10.21.188.219:4567/2685] - error: Error: listen EACCES: permission denied tcp://10.21.188.219:4567
    at Server.setupListenHandle [as _listen2] (node:net:1882:21)
    at listenInCluster (node:net:1961:12)
    at Server.listen (node:net:2080:5)
    at /usr/src/app/src/webserver.js:291:10
    at new Promise (<anonymous>)
    at listen (/usr/src/app/src/webserver.js:290:9)
    at async exports.listen (/usr/src/app/src/webserver.js:95:2)
    at async start.start (/usr/src/app/src/start.js:45:3
```
I haven't got to the root cause, but if we can override the environmental variable for bind_address:
https://github.com/NodeBB/NodeBB/blob/be32cf4404f5f71c3e2d01d9f57dc5d7d29c4d87/src/webserver.js#L276-L304

Then we can use the K8S downward API to force binding on the pod address only:
```yaml
          env:          
            - name: bind_address
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
```
And work around the entire issue. I saw a similar issue on [stackoverflow](https://stackoverflow.com/questions/77246674/kubernetes-service-ip-used-for-node-application-listen-error-listen-eacces) and I'm not sure if it is also something Node specific
