### ISSUE TITLE
Automated setup from a config file

### ISSUE THREAD

**Issue by batchor** [NodeBB/NodeBB#12958]
### Description

Currently, the `nodebb setup` command requires several interactive inputs. Especially, it requires database information to connect to db at setup. This is really awkward in containerized deployment.

In my case, I deploy NodeBB instance with docker compose where one container runs mongodb and the other one runs NodeBB.

I have to start the services, and then go inside the NodeBB container to execute `nodebb setup`, and interactively provide mongodb as well as admin information.

It's way better to setup during docker image building from a simple config file, and connect to the db in runtime. I don't know how others automate the deployment. If anyone has better solution, I'm glab to hear.

Also discussed here <https://community.nodebb.org/topic/15253/how-to-setup-admin-user-in-config-json-in-nodebb/6>

**Comment by khassel** [comment]
I implemented following workaround for this:
- build the docker image for NodeBB (adding all needed plugins)
- use this image in a ci job (I use gitlab) and add a new mongo db as service
- activate all plugins and run `nodebb build`
- save the `build` dir
- add the `build` dir files to your image

With this I have everything in the docker image which is needed to run new nodebb versions with minimal downtime and without doing manual steps inside the container.

But I would prefer a better and simpler solution!

Here the build step using a fresh mongo db for producing the build files:

```yaml
variables:
  NODE_BB_PLUG_ACTIVATE: "nodebb-theme-persona nodebb-plugin-2factor nodebb-plugin-composer-default nodebb-plugin-dbsearch nodebb-widget-essentials nodebb-plugin-custom-pages nodebb-plugin-recent-cards nodebb-plugin-mentions nodebb-plugin-markdown nodebb-plugin-emoji nodebb-plugin-question-and-answer nodebb-rewards-essentials nodebb-plugin-spam-be-gone"

...

init_nodebb:
  stage: build_artefacts
  extends: .jobdefaultsnodebb
  image:
    name: your_nodebb_image
    entrypoint: [""]
  services:
    - name: mongo:7-jammy
      variables:
        MONGO_INITDB_ROOT_USERNAME: nodebb
        MONGO_INITDB_ROOT_PASSWORD: nodebb
  script:
    - |
      cd /usr/src/app
      ls -la
      cat <<EOF >> config.json
      {
          "url": "http://localhost:4567",
          "secret": "abc",
          "database": "mongo",
          "port": "4567",
          "mongo": {
              "host": "mongo",
              "port": "27017",
              "username": "nodebb",
              "password": "nodebb",
              "database": "admin",
              "uri": ""
          }
      }
      EOF
      for item in $NODE_BB_PLUG_ACTIVATE; do eval ./nodebb activate $item; done
      ./nodebb build
      cp -r build/ ${CI_PROJECT_DIR}
  artifacts:
    paths:
      - build/
```
