### ISSUE TITLE
Invalid LESS in Custom CSS bricks NodeBB

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#1715]
Adding a custom CSS of:

``` LESS
body {
    background-color: #derp-a-derp;
}
```

Causes the LESS parser to explode and bricks a NodeBB because the custom CSS cannot be cleared.
