### ISSUE TITLE
Why is there a 'display: none;' in color picker's submit button?

### ISSUE THREAD

**Issue by xusoo** [NodeBB/NodeBB#2653]
https://github.com/NodeBB/NodeBB/blob/master/public/vendor/colorpicker/colorpicker.css#L142

```css
.colorpicker_submit {
    display: none;
    ...
}
```

It affects other plugins like the 'nodebb-plugin-color'. If doesn't appear the submit button, the user cannot choose a color (if the event is onSubmit instead of onChange)

I checked the [original code](http://www.eyecon.ro/colorpicker/) and there isn't a `display: none;` at that line.
