### ISSUE TITLE
Chat and notification avatars are square

### ISSUE THREAD

**Issue by henrywright** [NodeBB/NodeBB#3484]
For consistency, chat and notification avatars could be made round to match the rest of the site. Currently they're square:

![notifications](https://cloud.githubusercontent.com/assets/1963288/9451472/c349ecc4-4aa6-11e5-8154-87017cad3258.png)

This should do it:
```CSS
.header #chat-list img,
.chats-list img,
.header #notif-list img,
.notifications-list img {
    border-radius: 50%;
}
```
