### ISSUE TITLE
Custom themes must use Bootstrap

### ISSUE THREAD

**Issue by henrywright** [NodeBB/NodeBB#3525]
The Less files in [nodebb-plugin-composer-default](https://github.com/NodeBB/nodebb-plugin-composer-default) seem to use Bootstrap variables. This results in errors when using themes that don't use Bootstrap.

**Comment by henrywright** [comment]
There's also:

 - `@gray-lighter` in nodebb/public/less/generics.less
 - `@state-info-text` in nodebb-plugin-mentions/static/style.less

**Comment by julianlam** [comment]
... are there themes that don't use Bootstrap? :smile:

**Comment by henrywright** [comment]
Probably not, due to these errors. :stuck_out_tongue:

**Comment by henrywright** [comment]
@julianlam I'm happy to take a look at this if you think it's worth doing?

**Comment by psychobunny** [comment]
I don't think we should force NodeBB themes to use bootstrap. That said, LESS (unlike SCSS) does not have a way to define something "if it hasn't been defined".

Bootstrap 4 will be in SCSS, and we do want to migrate our primary themes to that. So I think this can be left on the backburner for today.

If you have a custom theme that does not use bootstrap, please just include those @variables in your LESS for now. :) 

(open for discussion though, happy to reopen)

**Comment by henrywright** [comment]
OK no problem. In case it's useful, this is what I had to do in my style.less:

```less
@btn-primary-bg: #000;
@btn-primary-color: #000;
@shadow: inset 0 0 0 #000;
@gray-light: #000;
@gray-lighter: #000;

.box-shadow(@shadow) {
	-webkit-box-shadow: @shadow;
			box-shadow: @shadow;
}
```
