### ISSUE TITLE
Flag page CSS incorrect when cold loaded

### ISSUE THREAD

**Issue by julianlam** [NodeBB/NodeBB#4584]
This is an odd one...

Go to `/admin/manage/flags`, observe bad CSS
Type `ajaxify.refresh()` into console, observe good CSS.

**Comment by julianlam** [comment]
Odd, the page classes were not applied to templates in ACP. So theme designers can now apply styles to ACP pages too I guess...

``` less
.admin .page-manage-flags {
  background: red;
}
```
