### ISSUE TITLE
403 Forbidden with socket.io when running on subdirectory behind NGINX

### ISSUE THREAD

**Issue by guateandrew** [NodeBB/NodeBB#5887]
I have read numerous reports and fixes for socket.io problems behind NGINX but none deal with running nodebb on a subdirectory.

- NodeBB version: 1.51 (via benlubar/nodebb:v1.5.x)
- Database type:redis

While I can load a forum page/admin menu etc, all the socket.io calls fail with 403 Fobidden.
```
**Nodebb config**
{
  "url":"http://127.0.0.1:4567/community",
  "database": "redis",
  "redis": {
    "host": "redis",
    "port": "6379"
  }
}
```
**nginx config**
```
server { # simple reverse-proxy
  listen       80;
  access_log   logs/all.access.log  main;
 location /community {
  proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $http_host;
    proxy_set_header X-NginX-Proxy true;
    proxy_pass http://community:4567/community;
    proxy_redirect off;
    # Socket.IO Support
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}
```
**Docker compose**
```
community:
    image: server-forum-development
    ports:
      - "4567:4567"
    links:
      - "redis:redis"
nginx:
    image: server-nginx-development
    ports:
      - "80:80"
    links:
      - "community:community"
```
**External values**
redis points for my redis host
community points to the nodebb host

Thanks all.
