### ISSUE TITLE
Add option to hide deleted posts

### ISSUE THREAD

**Issue by tom-rade** [NodeBB/NodeBB#7291]
Add an option in the admin panel to completely hide deleted posts for registered users (hide the "This post was deleted" message). When deleting a lot of posts it would make topics look more organizied. Just a suggestion.

**Comment by pauljherring** [comment]
[/admin/appearance/customise](#)

```css
ul.posts li.deleted {
    display: none;
}
```

should probably do it.

**Comment by pauljherring** [comment]
Might want to announce such a change however, since it will render any controls to undelete it unavailable to everyone.

**Comment by tom-rade** [comment]
@pauljherring Oh, fine then. Thanks.

**Comment by pauljherring** [comment]
That only deals with viewing the posts in a topic btw, for the category list if whole topics have been deleted, you also probably want:

```css
ul.topic-list li.row.deleted {
    display: none;
}
```
