### ISSUE TITLE
Wrong redirection with repeated url like https://example.com/https://example.com after login

### ISSUE THREAD

**Issue by blurHY** [NodeBB/NodeBB#7323]
- 1.11.2
- **NodeBB git hash:**  I tried to debug it,so I added a line of `console.log`
- **Database type:** mongo
- **Database version:** 3.6.10

I'm using nodebb in docker behind nginx.

Nginx config:
```nginx
    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://127.0.0.1:8081;
        proxy_redirect off;
# Socket.IO Support
        proxy_http_version 1.1;
    }
```

docker-compose.yml:

```yml
version: "3"
services:
  nodebb_db:
    image: mongo:3.6
    command: ['mongod', '--auth', '--bind_ip_all']
    networks:
      - default
      - nodebb_net
    ports:
      - "39517:27017"    
    volumes:
      - "./dbIniter/:/docker-entrypoint-initdb.d/"
      - "/mnt/data/nodebb:/data/db"
      - "/mnt/backup/nodebb:/backup"
      - "./configs.json:/etc/nodebb/configs.json"
    restart: always
    environment:
     - TZ=Asia/Shanghai
  nodebb:
    image: nodebb/docker
    links: 
      - nodebb_db
    restart: always
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - "8081:4567"
    networks:
      - default
      - nodebb_net
    environment:
     - TZ=Asia/Shanghai
networks:
 nodebb_net:
  external: true
```

I tried to use different user or browser to log in and cleared cache and cookie, but it still happens
