### ISSUE TITLE
Unable to connect to PostgreSQL that doesn't support SSL

### ISSUE THREAD

**Issue by Octobug** [NodeBB/NodeBB#7892]
- **NodeBB version:** `master` branch
- **NodeBB git hash:** 9b4ae4c04afaa770c2c04e0169f918e94bec66cf
- **Database type:** postgres
- **Database version:** 11.5 (I think it doesn't matter what the version is)
- **Exact steps to cause this issue:**

1. First I wrote the `docker-compose.yaml` as below:
```yaml
version: "3.1"
services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - "/<some_path>/docker_volumes"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nodebb  
  nodebb:
    image: nodebb/docker
    container_name: nodebb
    ports:
      - "4567:4567"
    restart: always
```

2. Then, I ran `docker-compose up`, accessed NodeBB Setup screen, filled out the setup form and submitted. The important item is that I set `Enable SSL for PostgreSQL database access` as `false` as the image below:
![image](https://user-images.githubusercontent.com/8007022/64618663-4181bf00-d413-11e9-82d0-930356c08879.png)

- **What you expected:**
NodeBB should setup database and go to its next step.

- **What happened instead:**
I got error from docker-compose command line as below:
```
nodebb | Now configuring postgres database:
nodebb | 2019-09-10T12:20:40.344Z [17] - error: NodeBB could not connect to your PostgreSQL database. PostgreSQL returned the following error: The server does not support SSL connections
nodebb | 2019-09-10T12:20:40.345Z [17] - warn: NodeBB Setup Aborted.
```

It is probably because there is the `ssl` config added by the commit which I have pointed out at `NodeBB git hash`(9b4ae4c04afaa770c2c04e0169f918e94bec66cf). While the PostgreSQL container didn't support sslmode. 

If this is the cause of the error then the `ssl` config should not appears in `connOptions` when `Enable SSL for PostgreSQL database access` is set to `false`.

Thanks!
