### ISSUE TITLE
feat: support `yaml` config file

### ISSUE THREAD

**Issue by greenhat616** [NodeBB/NodeBB#8259]
# why?
* `yaml` is easy to read and write
* it can cause less grammer issues than json
  * newbie might use `"`, `,` in wrong way, and old `vim` or `vi` can't provide lint program
    * they should use json lint website, like: https://jsonlint.com/
  * yaml can avoid these issues.
* it might be a enhancement feature, and can be imported in NodeBB v2.x, etc?
# example
```yaml
url: http://127.0.0.1:4567
secret: 24a6d5cc-904a-44a9-b255-db6f2c802ca7
database: redis
redis:
  host: 127.0.0.1
  port: 6379
  password:
  database: 0
port: 4567
package_manager: yarn
```

# How to integrate it？
* use `nconf-yaml` package to let `nconf` support it
  * both support `config.yml` and `config.json`
  * use `config.yml` as default config format
