### ISSUE TITLE
Connection refused when I tried to install nodebb using docker-compose

### ISSUE THREAD

**Issue by trprado** [NodeBB/NodeBB#9455]
- **NodeBB version:** v1.16.2
- **NodeBB git hash:** 023e4cfcee208a0bae121a6e343a8c53009fd090
- **NodeJS version:** v14.16.0

- **Installed NodeBB Plugins:** 

- **Database type:** mongo
- **Database version:** v4.4.4

- **Exact steps to cause this issue:**

When I initiated the install process using docker-compose, my nodebb received a response of connection refused. I tested the connection using mongo-express and all occurred as expected.

My docker-compose file:
```YAML
version: '3.5'

services:

  traefik:
    image: traefik:v2.4
    restart: unless-stopped
    container_name: "traefik-mongo"
    privileged: true
    command:
      # - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  node:
    build: .
    restart: unless-stopped
    privileged: true
    depends_on:
      - mongo
    expose: 
      - 4567
    labels: 
      - traefik.enable=true
      - traefik.http.routers.node.rule=Host(`node.localhost`)
      - traefik.http.routers.node.entrypoints=web
      - traefik.http.services.node.loadbalancer.server.port=4567
      - traefik.docker.network=web

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    expose: 
      - 27017
    volumes:
      - mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    privileged: true
    expose:
      - 8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on: 
      - mongo
    labels: 
      - traefik.enable=true
      - traefik.http.routers.express.rule=Host(`express.localhost`)
      - traefik.http.routers.express.entrypoints=web
      - traefik.http.services.express.loadbalancer.server.port=8081
      - traefik.docker.network=web

volumes:
  mongo:
```
- **What you expected:**

Install nodebb in mongo database.
- **What happened instead:**

These errors occurred when I upped the containers and tried to install nodebb:
```logger
node_1           | 2021-04-02T17:21:03.623Z [3] - info: Starting setup process
node_1           | 2021-04-02T17:21:03.624Z [3] - info: [object Object]
node_1           | 2021-04-02T17:21:03.884Z [14] - info: NodeBB Setup Triggered via Command Line
node_1           | 
node_1           | Welcome to NodeBB v1.16.2!
node_1           | 
node_1           | This looks like a new installation, so you'll have to answer a few questions about your environment before we can proceed.
node_1           | Press enter to accept the default setting (shown in brackets).
node_1           | 2021-04-02T17:21:03.941Z [14] - info: 
node_1           | Now configuring mongo database:
node_1           | 2021-04-02T17:21:34.016Z [14] - warn: NodeBB Setup Aborted.
node_1           |  MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
node_1           |     at Timeout._onTimeout (/usr/src/app/node_modules/mongodb/lib/core/sdam/topology.js:438:30)
node_1           |     at listOnTimeout (internal/timers.js:554:17)
node_1           |     at processTimers (internal/timers.js:497:7)
```
